
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = 'X\xdey\xf1xL\x89h7j\r\x97\xac\xd8mS'

_lr_action_items = {'RPAREN':([10,8,2,5,3,7,12,9,11,4,6,],[-3,-9,-4,-5,-4,-6,-1,-8,-2,-7,12,]),'STRING':([4,9,5,3,12,7,8,2,],[-7,-8,-5,4,-1,-6,-9,4,]),'LPAREN':([4,9,5,3,7,2,8,12,0,],[-7,-8,-5,2,-6,2,-9,-1,2,]),'INT':([9,12,4,8,7,2,5,3,],[-8,-1,-7,-9,-6,5,-5,5,]),'SYMBOL':([7,5,8,2,3,4,9,12,],[-6,-5,-9,9,9,-7,-8,-1,]),'FLOAT':([9,12,4,8,2,7,3,5,],[-8,-1,-7,-9,7,-6,7,-5,]),'$':([12,1,],[-1,0,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'node':([3,2,],[3,3,]),'nodes':([2,3,],[6,11,]),'list':([2,0,3,],[8,1,8,]),'empty':([2,3,],[10,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
